name: Deploy to production

on:
  push:
    tags:
    - v*

jobs:
  aws_cdk:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Setup dependencies
        run: npm ci

      - name: Build
        run: npm run build
          
      - name: CDK RPD Diff Check
        run: npm run cdk:prd-diff
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: CDK PRD Deploy
        if: contains(github.event_name, 'push')
        run: npm run cdk:prd-deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
