name: eslint
on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/eslint.yml'
      - '**.md'
    types: [opened, synchronize]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    if: github.event.pusher.name != 'dreamkast-cloudnativedays'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install
        run: npm install

      - name: eslint
        run: npm run lint
